### ISSUE TITLE
SolrCoreAdmin malfunction

### ISSUE THREAD

**Issue by pdelboca** [django-haystack/pysolr#186]
Using the SolrCoreAdmin I have spotted some errors. (I'm glad to fix them with some guidance.)

##### Problem:
When calling the `_get_url` method, the `params` argument is being use to override the data argument of requests.get. It should be used to replace the `params` argument instead. 

This is the current code:

```python 
def _get_url(self, url, params={}, headers={}):
        resp = requests.get(url, data=safe_urlencode(params), headers=headers)
        return force_unicode(resp.content)
```
This causes **all the methods** of the SolrCoreAdmin to malfunction because they call only the main URL (http://localhost:8983/solr/admin/cores) without the parameters. The tests check if the response of those calls contains `''<int name="status">0</int>''`, however, when calling to the main URL solr reponse with some data about the cluster and always returns status = 0. So tests aren't actually testing correctly neither.

I'm missing something important here o is this a bug in this class? If so...

##### Proposal:
Changing `requests.get` to use `params` instead of `data` will make the _get_url work properly. I did that with the status method correctly but I'm struggling with the test to the create function that needs to upload the solrconfig.xml and schema.xml files with the call to the url. 

Should I upload those files to the repo under the test folder? How would you approach this? With some guidance I'm sure I can fix the problem.

**Comment by nikos** [comment]
When using Solr 6.5.1 with pysolr the core admin functionality seems still not to work properly. It seems like the problem has not been fixed on the master branch yet.

When switching the implementation of _get_url (params=params) as proposed by @pdelboca  the corresponding test cases are failing:

```
======================================================================
FAIL: test_create (tests.test_admin.SolrCoreAdminTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/niko/sandbox/python/pysolr/tests/test_admin.py", line 21, in test_create
    self.assertTrue('<int name="status">0</int>' in status)
AssertionError: False is not true

======================================================================
FAIL: test_reload (tests.test_admin.SolrCoreAdminTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/niko/sandbox/python/pysolr/tests/test_admin.py", line 24, in test_reload
    self.assertTrue('<int name="status">0</int>' in self.solr_admin.reload('wheatley'))
AssertionError: False is not true

======================================================================
FAIL: test_rename (tests.test_admin.SolrCoreAdminTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/niko/sandbox/python/pysolr/tests/test_admin.py", line 28, in test_rename
    self.assertTrue('<int name="status">0</int>' in self.solr_admin.rename('wheatley', 'rick'))
AssertionError: False is not true

======================================================================
FAIL: test_swap (tests.test_admin.SolrCoreAdminTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/niko/sandbox/python/pysolr/tests/test_admin.py", line 33, in test_swap
    self.assertTrue('<int name="status">0</int>' in self.solr_admin.swap('wheatley', 'rick'))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 96 tests in 2.386s

FAILED (failures=4, skipped=41)
```

The response message from the create core call looks like:

```
<response>
<lst name="responseHeader"><int name="status">400</int><int name="QTime">13</int></lst><lst name="error"><str name="msg">Error CREATEing SolrCore 'wheatley': Unable to create core [wheatley] Caused by: Can't find resource 'solrconfig.xml' in classpath or '/Users/niko/sandbox/python/pysolr/solr/non-cloud/wheatley/conf'</str><int name="code">400</int></lst>
</response>
```
