### ISSUE TITLE
Is there any way to add a pdf file to solr?

### ISSUE THREAD

**Issue by aodavid** [django-haystack/pysolr#206]

**Comment by acdha** [comment]
Yes, if your Solr install has enabled the Content Extraction handler enabled, it's simply a matter of using the Pysolr `extract` method which supports PDF, Microsoft Office, etc.:

https://github.com/django-haystack/pysolr/blob/master/pysolr.py#L973

**Comment by aodavid** [comment]
Thanks for your reply, But i met following issue with codes:
`    filename = "test.pdf"
    doc = {
                "id": "test"
            }
    with open(filename, "r") as f:
         solr.extract(file_obj=f, **doc)`
issue:
`pysolr.SolrError: Solr responded with an error (HTTP 400): [Reason: missing content stream]`
I removed doc
`filename = "test.pdf"
    with open(filename, "r") as f:
         solr.extract(file_obj=f)`
It still not work, do i use it with wrong way? can you help me ? thx very much.

**Comment by acdha** [comment]
PDF files are binary so you probably need to open the file "rb". Otherwise, this could be an error in your Solr installation which you'd need to check the logs to investigate further.

The pysolr test suite uses an HTML file (https://github.com/django-haystack/pysolr/blob/master/tests/test_client.py#L725-L764) but the test for the corresponding Django-Haystack feature uses a test PDF opened in binary mode:

https://github.com/django-haystack/django-haystack/blob/42f53cda9a770ff7daf2ff792cbcab5cd843e2a7/test_haystack/solr_tests/test_solr_backend.py#L1451-L1455

**Comment by aodavid** [comment]
It still don't work, the errors in log:
`ERROR - 2016-10-25 02:50:17.928; org.apache.solr.common.SolrException; org.apache.solr.common.SolrException: missing content stream
        at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:69)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
        at org.apache.solr.core.RequestHandlers$LazyRequestHandlerWrapper.handleRequest(RequestHandlers.java:241)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:1952)
        at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:774)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:418)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)`

Besides, it works when i use pycurl with solr REST API. but i still want to use your API if it is possible
