### ISSUE TITLE
pysolr Solrcloud won't recognize the collection

### ISSUE THREAD

**Issue by r1qu3** [django-haystack/pysolr#226]
# I have
* [x] Tested with the latest release
* [x] Tested with the current master branch
* [x] Searched for similar existing issues

## Expected behaviour
find the collection so i could use pysolr.SolrCloud().add() to write my json documents.

## Actual behaviour
I can connect to zookeeper but pysolr won't find my collection (collection name):
"
Traceback (most recent call last):
  File "/home/rique/PycharmProjects/solrOficios/persist.py", line 15, in <module>
    solrCollectionDestino = pysolr.SolrCloud(zookeeper=solrZookeeper, collection='aaa', timeout=60)
  File "/usr/local/lib/python3.5/dist-packages/pysolr.py", line 1178, in __init__
    url = zookeeper.getRandomURL(collection)
  File "/usr/local/lib/python3.5/dist-packages/pysolr.py", line 1317, in getRandomURL
    hosts = self.getHosts(collname, only_leader=only_leader)
  File "/usr/local/lib/python3.5/dist-packages/pysolr.py", line 1283, in getHosts
    raise SolrError("Unknown collection: %s" % collname)
pysolr.SolrError: Unknown collection: aaa
"
## Steps to reproduce the behaviour

1.
zkHost1 = 'xxx:2181'
zkHost2 = 'yyy:2181'
zkHost3 = 'zzz:2181'

2.
solrZookeeper = pysolr.ZooKeeper(zkServerAddress='{},{},{}'.format(zkHost1, zkHost2, zkHost3), timeout=60)

3.
solrCollectionDestino = pysolr.SolrCloud(zookeeper=solrZookeeper, collection='aaa', timeout=60)

## Configuration

* Operating system version: Ubuntu 16.04
* Search engine version: Solr 6.3.0
* Python version: 3.5.2
* pysolr version: 3.6.0

**Comment by yuzhou6** [comment]
@r1qu3 I do not know if this a problem, you can try to check the hosts file. 

`cat /etc/hosts` 

and add the zookeeper IP, like:

```
10.76.86.xx     solr01.hadoop.ps
10.76.86.xx     solr02.hadoop.ps
10.76.86.xx     solr03.hadoop.ps
```

` solr01.hadoop.ps` is your zookeeper hostname

**Comment by han058** [comment]
1) 
before create instance,
set variable like below,

pysolr.Zookeeper.CLUSTER_STATE=/clusterstate.json

2)
In solr admin,
change alias, and
copy from /collections/your_new_collection_name/state.json to /clusterstate.json via zk client ( like ./bin/solr zk cp zk:/collections/your_new_collection_name/state.json zk:/clusterstate.json
