### ISSUE TITLE
Installing 3.9.0 release via pip is somehow broken

### ISSUE THREAD

**Issue by don-philipe** [django-haystack/pysolr#384]
Hello,

I have a problem with the installation of the current 3.9.0 release and I can't figure out where the problem comes from. The installation via `pip` is somehow broken since yesterday. Before yesterday everything worked fine.

My temporary solution is to switch back to the 3.8.1 release which I can install without problems.

# I have
* [x] Tested with the latest release
* [x] Tested with the current master branch
* [x] Searched for similar existing issues

## Expected behaviour

`pysolr` should be installable via `pip install -r requirements.txt` in a virtual environment.

## Actual behaviour

Installation via `pip install -r requirements.txt` leads to the following error:

```
Collecting pysolr==3.9.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/9c/c6/9f0b80f17747db12acbdf421a22acdad23c93eea7046181ae6ebdf427bfd/pysolr-3.9.0.tar.gz (55kB)
    100% |████████████████████████████████| 61kB 27.5MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-k5bccgt8/pysolr/setup.py", line 29, in <module>
        setup_requires=["setuptools_scm"],
      File "$HOME/pysolr-test/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "$HOME/pysolr-test/venv/lib/python3.6/site-packages/setuptools/dist.py", line 442, in __init__
        k: v for k, v in attrs.items()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "$HOME/pysolr-test/venv/lib/python3.6/site-packages/setuptools/dist.py", line 601, in finalize_options
        ep.load()(self, ep.name, value)
      File "$HOME/pysolr-test/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
        return self.resolve()
      File "$HOME/pysolr-test/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/tmp/pip-install-k5bccgt8/pysolr/.eggs/setuptools_scm-7.0.3-py3.6.egg/setuptools_scm/__init__.py", line 5
        from __future__ import annotations
        ^
    SyntaxError: future feature annotations is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-k5bccgt8/pysolr/
```

## Steps to reproduce the behaviour

1. create virtual environment via `python3 -m venv venv` and activate it with `source venv/bin/activate`
2. put `pysolr==3.9.0` into a file named `requirements.txt`
3. run `pip install -r requirements.txt`

## Configuration

* Operating system version: Ubuntu 21.10, CentOS 7
* Search engine version: 8.11.1
* Python version: 3.6.13
* pysolr version: 3.9.0

**Comment by don-philipe** [comment]
Tested it now with version `3.10.0b1` which seems to be the current master. The result is the exact same as with version 3.9.0 for me.

**Comment by acdha** [comment]
This is an issue with using an unsupported version of Python (3.6 hit EOL last year) and a current version of setuptools_scm. If you need to use Python 3.6 you'll need to pin an older version of setuptools_scm in your environment.
