### ISSUE TITLE
TypeError: Element() keywords must be strings

### ISSUE THREAD

**Issue by srusskih** [django-haystack/pysolr#72]
```
Traceback (most recent call last):
  File "/storage/pydev/feelfree-v4/feelfree/../lib/haystack/management/commands/update_index.py", line 210, in handle_
label
    self.update_backend(label, using)
  File "/storage/pydev/feelfree-v4/feelfree/../lib/haystack/management/commands/update_index.py", line 256, in update_
backend
    do_update(backend, index, qs, start, end, total, self.verbosity)
  File "/storage/pydev/feelfree-v4/feelfree/../lib/haystack/management/commands/update_index.py", line 78, in do_updat
e
    backend.update(index, current_qs)
  File "/storage/pydev/feelfree-v4/feelfree/../lib/haystack/backends/solr_backend.py", line 66, in update
    self.conn.add(docs, commit=commit, boost=index.get_field_weights())
  File "/storage/pydev/feelfree-v4/feelfree/../lib/pysolr.py", line 740, in add
    message.append(self._build_doc(doc, boost=boost))
  File "/storage/pydev/feelfree-v4/feelfree/../lib/pysolr.py", line 695, in _build_doc
    field = ET.Element('field', **attrs)
  File "lxml.etree.pyx", line 2560, in lxml.etree.Element (src/lxml/lxml.etree.c:52924)
TypeError: Element() keywords must be strings
```

attrs looks like `{u'name': 'django_ct'}`

**env:**
- Linux 3.5.0-22-generic #34-Ubuntu SMP Tue Jan 8 21:47:00 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
- python 2.7.3
- pysolr 3.0.5
- lxml 2.3.5

Possible fix (works for me)

``` diff
@@ -687,10 +687,10 @@ class Solr(object):
                 if self._is_null_value(bit):
                     continue

-                attrs = {'name': key}
+                attrs = {str('name'): key}

                 if boost and key in boost:
-                    attrs['boost'] = force_unicode(boost[key])
+                    attrs[str('boost')] = force_unicode(boost[key])

                 field = ET.Element('field', **attrs)
                 field.text = self._from_python(bit)
```

**Comment by tisto** [comment]
I just ran into that issue (from 2013?). Wouldn't it be better to make pysolr require a certain lxml version in its setup.py to avoid problems like this?

**Comment by acdha** [comment]
@tisto The problem was that people had other versions of lxml in their projects & it'd conflict for something which is only relevant to a subset of users. My preferred approach is the one from https://github.com/toastdriven/pysolr/pull/133#issuecomment-60452949 where we simply drop lxml entirely since it's only used for error handling. I just wrapped that code into #149 for easier testing / commenting.
